### ISSUE TITLE
Use MIT license

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/Keter#64]
I've noticed that our **bestest** Keter project still haven't mentioned a license!

So I need to get a consent of **every** contributor to license their _existing_ contribution in Keter under the MIT license.

Please state your consent, guys. If you not, I'll have to exclude your contribution from the code base and probably rewrite it myself.

- [x] @Akon32 
- [x] @ForNeVeR
- [x] @IngvarJackal 
- [x] @hagane

**Comment by IngvarJackal** [comment]
I don't mind, MIT license is suitable for my contribution.

**Comment by hagane** [comment]
As far as I care, everything I release to general public without explicit license statement is available under WTFPL. So yeah, feel free to slap a MIT License on it.
Wait, that reminds me. Wouldn't CC-BY-SA be more suitable for non-code parts, like game design documents and art assets?

**Comment by ForNeVeR** [comment]
Regarding the documentation: MIT explicitly mentions it in `this software and associated documentation files (the "Software")`.

Regarding the assets: this kinda complicates the story. Couldn't we just count them as part of "this software"?

**Comment by hagane** [comment]
It's a gray area, esp. if someone would want to use said assets in another project. There be legalese-breathing dragons. Separate license for assets will clarify a lot of use cases. Though it will marginally complicate our process too.

**Comment by ForNeVeR** [comment]
Alright then. Right now we have no assets aside of the documentation, which is covered by MIT. So I think that MIT will be enough for now. Later, when/if we add any other kind of assets, we'll clarify the licensing to cover it.

**Comment by Akon32** [comment]
Okay, MIT license is suitable.

**Comment by ForNeVeR** [comment]
Thank you guys. I will sort out the remaining issues, create a license PR, and merge the existing PRs in the nearest time.
